# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Metum

# Model Form Field configuration
form: $/ratmd/bloghub/models/metum/fields.yaml

# Model Class name
modelClass: RatMD\BlogHub\Models\Metum

# Default redirect location
defaultRedirect: ratmd/bloghub/meta

# Create page
create:
    title: backend::lang.form.create_title
    redirect: ratmd/bloghub/meta/update/:id
    redirectClose: ratmd/bloghub/meta

# Update page
update:
    title: backend::lang.form.update_title
    redirect: ratmd/bloghub/meta
    redirectClose: ratmd/bloghub/meta

# Preview page
preview:
    title: backend::lang.form.preview_title
